### PR TITLE
Fixes to "more" bug, UI nonresponsiveness, and performance; some tests and refactoring

### PR DESCRIPTION
**Pull request by FoxLisk**
I don't know if you're interested in PRs here/if this is maintained at all, but I figured I'd at least throw it over the wall.

I also am not very familiar with the C#/MS toolchain stuff, so I'm not sure if updates to the config files about .NET version and such are supposed to be in here?

There's a lot in here (sorry); the main points are reducing the number of connection tests (which are currently blocking, which is a different issue that I haven't gotten to yet), and fixing the bug where a split with a "more" attribute was not being tested correctly; it was comparing the target value against the memory read from its parent split's address.

### CODE REVIEW

**Comment by Skarsnik** [comment]
You should probably remove some VS config file change, Don't really need the latest .net framework version x)
Please try to keep the else keyword with the } { it's easier to see that it's associated with a if block.

I am not really a big C# expert to give you better input thou.

**Comment by FoxLisk** [comment]
The reason I bumped the .NET framework version is that the newest LiveSplit code uses 4.6.1, which caused issues building this project against it. If you don't want to roll the framework version forward, that's totally fair, but it does mean I will probably have to maintain my fork instead of being able to contribute fixes like this upstream. Your call.

I'm not sure what you mean about the else thing exactly. Are you saying you prefer

```
if ()
{
} else
{
}
```

over

```
if ()
{
}
else
{
}
```

? All I did was run the default Visual Studio formatter, so if that's what you mean I'm sure I can talk it into formatting that way instead.

**Comment by Skarsnik** [comment]
It's more like
if ()
{
} else {
}

My bad for the .net version I though it was like 4.5 to 6.2 x)

**Comment by FoxLisk** [comment]
Okay, I updated the formatting. And yeah, the version bump was just a minor version to get in line with the LiveSplit code base.

**Comment by Skarsnik** [comment]
Thanks !

**Pull request merged**
