### PR TITLE
Add optional status message

### PR DESCRIPTION
**Pull request by Bonus36**
These changes add a status message to provide a little more information to new users than just the red/yellow/green color:

StatusMessage

In addition to the messages seen in the image, there are messages for a config error, failing to connect/attach, and failing to find the specified device name.

There is an option in the Layout Settings to enable/disable the status message. Disabling it makes the component's appearance the same as it was before this change. The option defaults to enabled when the autosplitter component is newly added, but disabled when loading old versions of the settings that did not include the option. So new users of this component (who this message is primarily aimed at) should see it, but existing users shouldn't see any change unless they intentionally turn it on.

In order to support this message, I changed the startup flow of the component to be more explicit in tracking exactly what state it's in with regard to reading the config file and attaching to the device, and also fixed a bug with `Usb2SnesW.Connect` that could cause its Task to never complete.

FYI, I have some other changes planned to make the setup of the config file/splits a little easier, so you may not want to do another release just for this change, but I can't say for sure when I'll have time to make those changes, so ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by Skarsnik** [comment]
Hm, very interesting, is there a way to autohide it after like being ready for some seconds? When it works fine it's kinda a waste of space for the user (and you can be limited in space with streaming).

**Comment by Bonus36** [comment]
Hmm, I was imagining it as a diagnostic tool - only turning it on when necessary. But yeah, that's a good point that if it auto-hid, you could just leave it on all the time. I'll look into doing that tonight.

**Comment by Bonus36** [comment]
Okay, I've updated it to auto-hide after 3 seconds of Ready. While doing this, I noticed that when the size of the autosplitter component changed, it would change the size of the whole timer, which meant that if you set a specific size in your layout settings, it would initially be the correct size, but then would change size when the Ready message hid. Since that seemed undesirable, I added some code to store the timer's size before updating the size of the autosplitter component, and then restore it to that same size after the autosplitter size changed.

I also added an auto-hide countdown to the message, so it's clear that the fact that "Ready" disappears does not mean that the autosplitter is no longer ready.

AutoHide

**Comment by Skarsnik** [comment]
Impressive work ! I wll probably do a nice release this week end ^^

**Comment by Skarsnik** [comment]
I forget to merge? x)

**Pull request merged**
