### PR TITLE
Support for subsplits and ability to turn off IGT

### PR DESCRIPTION
**Pull request by idlechild**
I added try-catch around IGT similar to other GetAddress calls, but also I don't find the IGT useful so I added an option to turn it off.  It is on by default.

Also I like what Bonus did with the categories, but it overrode the support for subsplits.  Any split starting with "-" is treated as a subsplit by the LiveSplit subsplit component, so if you name it "-Bombs", then it will show as "Bombs" in LiveSplit but it is treated as a subsplit.  The underlying segment name is still "-Bombs" though which means the auto-splitter can't match it up with anything in the json.  Added logic to removing leading hyphens so it can match up the split segment names.

Also added many definitions to the Super Metroid json file.

### CODE REVIEW

**Comment by Skarsnik** [comment]
The IGT should probably be on the json in some form and not in the component code.
Maybe could you do a separate pr for subsplits?

**Comment by idlechild** [comment]
I liked the idea to move the IGT definitions to the json file.  That allows users to choose if they want IGT or not and also removes the ugly "if super metroid" check from the code.  This is what it looks like in json:

  "igt": {
    "framesAddress": "0x09DA",
    "secondsAddress": "0x09DC",
    "minutesAddress": "0x09DE",
    "hoursAddress": "0x09E0"
  },

I haven't done a lot of testing, but the testing I have done shows it sets IGT when this is present and doesn't set it when this is not present.

**Comment by Skarsnik** [comment]
This should probably be an option in the setting to activate or not, could be annoying to have rewrite this if you want IGT later x)

**Comment by idlechild** [comment]
Added an "active" property similar to the autostart section.  Also took this opportunity to turn IGT off by default.

**Comment by Skarsnik** [comment]
Thanks :)

**Pull request merged**
